// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function DeleteConnectionProfile(arg1:string):Promise<void>;

export function ExecuteQuery(arg1:models.QueryRequest):Promise<models.QueryResult>;

export function GetSchema(arg1:models.SchemaRequest):Promise<models.SchemaInfo>;

export function KillQuery():Promise<boolean>;

export function ListConnectionProfiles():Promise<Array<models.ConnectionProfile>>;

export function ListDatabases(arg1:string):Promise<Array<string>>;

export function ListQueryHistory(arg1:number):Promise<Array<models.QueryHistory>>;

export function SaveCSVFile(arg1:string,arg2:string):Promise<string>;

export function SaveConnectionProfile(arg1:models.ConnectionProfileInput):Promise<models.ConnectionProfile>;

export function SetDefaultDatabase(arg1:string,arg2:string):Promise<models.ConnectionProfile>;

export function TestConnection(arg1:models.ConnectionProfileInput):Promise<models.ConnectionTestResult>;
