// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteConnectionProfile(arg1) {
  return window['go']['main']['App']['DeleteConnectionProfile'](arg1);
}

export function ExecuteQuery(arg1) {
  return window['go']['main']['App']['ExecuteQuery'](arg1);
}

export function GetSchema(arg1) {
  return window['go']['main']['App']['GetSchema'](arg1);
}

export function KillQuery() {
  return window['go']['main']['App']['KillQuery']();
}

export function ListConnectionProfiles() {
  return window['go']['main']['App']['ListConnectionProfiles']();
}

export function ListConnectionQueryHistory(arg1, arg2) {
  return window['go']['main']['App']['ListConnectionQueryHistory'](arg1, arg2);
}

export function ListDatabases(arg1) {
  return window['go']['main']['App']['ListDatabases'](arg1);
}

export function ListQueryHistory(arg1) {
  return window['go']['main']['App']['ListQueryHistory'](arg1);
}

export function SaveCSVFile(arg1, arg2) {
  return window['go']['main']['App']['SaveCSVFile'](arg1, arg2);
}

export function SaveConnectionProfile(arg1) {
  return window['go']['main']['App']['SaveConnectionProfile'](arg1);
}

export function SetDefaultDatabase(arg1, arg2) {
  return window['go']['main']['App']['SetDefaultDatabase'](arg1, arg2);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}
